import {
  SENTRY_IO_DSN,
  AMPLITUDE_ANALYTICS_KEY,
  BASE_ADMIN,
  BASE_SSO,
  MENU_LINKS_DOMAIN,
  SHOPIFY_API_KEY,
  TOKEN_KEY,
  SENTRY_ENVIRONMENT,
  BUILD_ENVIRONMENT,
  INTERCOM_USER_HASH_KEY_IOS,
  INTERCOM_USER_HASH_KEY_ANDROID,
} from 'react-native-dotenv';

export default {
  SENTRY_IO_DSN,
  AMPLITUDE_ANALYTICS_KEY,
  BASE_SSO,
  BASE_ADMIN,
  MENU_LINKS_DOMAIN,
  SENTRY_ENVIRONMENT,
  SHOPIFY_API_KEY,
  TOKEN_KEY,
  BUILD_ENVIRONMENT,
  INTERCOM_USER_HASH_KEY_IOS,
  INTERCOM_USER_HASH_KEY_ANDROID,
};
